### ISSUE TITLE
test_fromtimestamp fails

### ISSUE THREAD

**Issue by iliastsi** [freach/udatetime#26]
One of the tests fail on my system with:

```
======================================================================
FAIL: test_fromtimestamp (test_udatetime.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/udatetime/test/test_udatetime.py", line 78, in test_fromtimestamp
    self.assertEqual(udt.utcoffset(), timedelta(0))
AssertionError: datetime.timedelta(0, 7200) != datetime.timedelta(0)

----------------------------------------------------------------------
```

The test seems to be affected by my timezone settings, because if I run the tests with `TZ=US/Pacific` I get:

```
======================================================================
FAIL: test_fromtimestamp (test_udatetime.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/udatetime/test/test_udatetime.py", line 78, in test_fromtimestamp
    self.assertEqual(udt.utcoffset(), timedelta(0))
AssertionError: datetime.timedelta(-1, 57600) != datetime.timedelta(0)

----------------------------------------------------------------------
```

and when I set `TZ` to `UTC`, all tests pass.

**Comment by freach** [comment]
fix in 4ff8cae93c1c5c91f7beb87dd4115645fbde8396

`fromtimestamp()` returns in local time, so the offset needs to be calculated for the local zone.
